### ISSUE TITLE
[BUG]: plan not downgrading after backdated subscription date

### ISSUE THREAD

**Issue by stephentgrammer** [getlago/lago#215]
**Describe the bug**
When a plan is added with a subscription date prior to the current date, and then is set to downgrade to a lower plan within the next month, when the time comes for the downgrade, a month is added to the original plan.

**To Reproduce**
1. Add a plan to an existing customer with the subscription date almost a month ago.
2. Add a second plan that is a downgrade from the first plan. The downgrade will say it is scheduled to happen in the next few days.
3. Wait until the downgrade is supposed to happen.
4. Watch a month get added to the original plan and the downgrade get postponed a month.

**Expected behavior**
When a downgrade is scheduled, it should actually happen.

**Screenshots**
This is the image of the original plan (subscription started on April 3rd, but backdated to March 4th) and the downgrade plan (named "NoPlan", which was also started on April 3rd). The original message below the plans was "downgrading to NoPlan on April 4th, 2023", but when April 4 came around, instead of downgrading, the original plan got another month and the message changed to this: 
![image](https://user-images.githubusercontent.com/36522622/229654360-fd630371-0692-4605-9ea1-b1681916727d.png)

**Support**
 - OS: the default lago docker container
 - Browser: Brave
 - Version: 5e9a053 misc(docker): bump to v0.26.0-beta (#206)

**Additional context**
We found this while trying to test the downgrade logic in our own application which we were hoping to trigger via webhook when then downgrade ran.

**Comment by mathieu-lago** [comment]
Hi @stephentgrammer - thanks for the detailed information. We'll try to reproduce it on our side and will get back to you with an update, most probably tomorrow.

**Comment by mathieu-lago** [comment]
Hi @stephentgrammer - we haven't been able to reproduce the bug you described. May I ask you to update to the latest version (`v0.27.0-beta`) and try again?

Also, did you create the subscriptions via the user interface or the API?

**Comment by stephentgrammer** [comment]
We are creating subscriptions via the user interface. I will have to postpone testing Lago `v0.27.0-beta` to next sprint, but I will comment again here after testing.

**Comment by stephentgrammer** [comment]
I was able to squeeze it in before the long Easter weekend. It still failed with 0.27.0 and pushed the downgrade out to May. I did not try with 0.28.0 since the lago javascript client didn't appear to have a matching version. Another thing I noticed while testing this is that the time/date settings don't seem to make sense, so I think I may have something configured incorrectly

When I select the 6th in the datepicker, it sets it to the 7th. 
![Screenshot from 2023-04-06 17-04-02](https://user-images.githubusercontent.com/36522622/230515315-322083b5-6760-4244-94c9-8a8dff12b9da.png)

When I choose the 7th, it sets it to the 8th.
![Screenshot from 2023-04-06 17-04-16](https://user-images.githubusercontent.com/36522622/230515471-6ae3ffce-a7a4-4ef3-ac2c-50d5b9378442.png)

But if I tried a few times I could get it to choose the 6th when I clicked the 6th. 
![Screenshot from 2023-04-06 17-05-52](https://user-images.githubusercontent.com/36522622/230515536-63621374-9f03-47d7-aef5-b29d26b3c606.png)

I also noticed that the timestamp on the subscription start time is in UTC, but the time is set to 06:59:59.
![Screenshot from 2023-04-06 17-05-07](https://user-images.githubusercontent.com/36522622/230515809-da438afc-790a-4f85-a1c3-eb8b397526a5.png)


I may not be understanding something, or maybe bad configuration, but this isn't quite behaving like I'd expect. Perhaps this is all related to why the plan downgrade is getting postponed?

**Comment by mathieu-lago** [comment]
Hi @stephentgrammer - we've released a fix related to the date picker in `v0.28.1-beta`.

Would you mind giving it a try?

**Comment by stephentgrammer** [comment]
The date picker is working as expected now. Thank you! However, the rest of the issue still exists:

I set up the subscription date as Mar 18 using the date-picker:
![Screenshot from 2023-04-17 15-53-27](https://user-images.githubusercontent.com/36522622/232635813-e677c23c-3658-439b-8761-566c21e769ee.png)

Downgraded the plan (note that it says it will downgrade on April 18):
![Screenshot from 2023-04-17 15-53-39](https://user-images.githubusercontent.com/36522622/232635981-7ae031e4-8fca-4ddc-833c-7051199b41c6.png)

The downgrade date changed to the 18th after I clicked the button:
![Screenshot from 2023-04-17 15-54-04](https://user-images.githubusercontent.com/36522622/232636155-18952497-3343-4aad-b973-1a54f245b9a9.png)

And then when midnight UTC April 18th came along, the downgrade date got bumped out a month into the future (and no webhook was sent):
![Screenshot from 2023-04-17 17-00-30](https://user-images.githubusercontent.com/36522622/232636316-55b759f2-1a0c-425c-be51-9dd034601073.png)

**Comment by mathieu-lago** [comment]
Hi @stephentgrammer - I've been able to reproduce this behaviour. I believe your clock and worker containers were not running when the downgrade was supposed to be actioned (i.e. during the night, between midnight and 01:00 AM UTC). Is this correct?

**Comment by stephentgrammer** [comment]
I just reran and confirmed that api-clock and api-worker from the lago docker compose file are both running. We're on 29.0 right now.
![image](https://user-images.githubusercontent.com/36522622/233511187-2753da7f-45cb-4c04-b842-b65060778da4.png)

**Comment by mathieu-lago** [comment]
That's actually my point: you shouldn't have to rerun Docker, these containers must be constantly running. If they're momentarily off, Lago cannot perform the scheduled jobs, which then get pushed back.

**Comment by stephentgrammer** [comment]
Sorry for the unclear communication! We are using the lago docker-compose.yml to run the test, so I confirmed that all the lago docker containers were running for the entirety of the test. So these are the steps I have been taking to reproduce the issue.

1. Start all the containers
2. Add a customer
3. Add a plan
4. Downgrade the plan
5. Wait for midnight UTC
6. Observe weird behavior
7. Shut down the containers

If you'd like, I'd be happy to communicate more directly with you and see if we can track down what's happening. I'm on PST, so I run the test at 5pm my time, which is midnight UTC.

**Comment by mathieu-lago** [comment]
Hi @stephentgrammer - we tried to reproduce this behaviour but did not succeed, except when the clock and worker containers were not running. The downgrade process seems to work well for other users. I'm afraid there's not much more we can do at this time.

I suggest that you review your Docker configuration. Please feel free to [join our community](https://www.getlago.com/slack) on Slack if you want to discuss this with other members.
