### ISSUE TITLE
[BUG]: Version 1.8.2 startup error reported

### ISSUE THREAD

**Issue by guleng** [getlago/lago#389]
version：1.8.2
Deployment method： docker-compose
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/c07e8e4c-dd89-4fb4-b8a2-b29e8735a74d">

I couldn't find the file scripts/start.migrate.sh

**Comment by jdenquin** [comment]
Hello @guleng, this should be fixed now

**Comment by guleng** [comment]
@jdenquin  The problem still exists, the file is missing from the image

**Comment by guleng** [comment]
@jdenquin Why is the 1.8.2 version of the Docker Composer image file you released still 1.8.1? Did you send the wrong version?

**Comment by jdenquin** [comment]
it's a problem we currently have in our release process, we'll change it next month, you can pull the repo and it should work 🙏

**Comment by guleng** [comment]
@jdenquin  It can start now, but the API service error log is as follows. Do I need to change the default configuration for my newly deployed one? Thank you for your answer
```
lago-api  | bin/rails aborted!
lago-api  | OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key (OpenSSL::PKey::RSAError)
lago-api  | /app/config/initializers/rsa_keys.rb:9:in `<main>'
lago-api  | /app/config/environment.rb:7:in `<main>'
lago-api  | Tasks: TOP => db:migrate => db:load_config => environment
lago-api  | (See full trace by running task with --trace)
lago-api  | bin/rails aborted!
lago-api  | OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key (OpenSSL::PKey::RSAError)
lago-api  | /app/config/initializers/rsa_keys.rb:9:in `<main>'
lago-api  | /app/config/environment.rb:7:in `<main>'
lago-api  | Tasks: TOP => signup:seed_organization => environment
lago-api  | (See full trace by running task with --trace)
lago-api  | => Booting Puma
lago-api  | => Rails 7.1.3.4 application starting in production 
lago-api  | => Run `bin/rails server --help` for more startup options
lago-api  | Exiting
lago-api  | /usr/local/lib/ruby/3.3.0/openssl/pkey.rb:356:in `initialize': Neither PUB key nor PRIV key (OpenSSL::PKey::RSAError)
lago-api  |     from /usr/local/lib/ruby/3.3.0/openssl/pkey.rb:356:in `new'
lago-api  |     from /usr/local/lib/ruby/3.3.0/openssl/pkey.rb:356:in `new'
lago-api  |     from /app/config/initializers/rsa_keys.rb:9:in `<main>'
lago-api  |     from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
lago-api  |     from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/engine.rb:690:in `block in load_config_initializer'
lago-api  |     from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:208:in `instrument'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/engine.rb:689:in `load_config_initializer'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/engine.rb:643:in `block (2 levels) in <class:Engine>'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/engine.rb:642:in `each'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/engine.rb:642:in `block in <class:Engine>'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `instance_exec'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `run'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:425:in `block (2 levels) in each_strongly_connected_component_from'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:424:in `block in each_strongly_connected_component_from'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:50:in `each'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:418:in `call'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:418:in `each_strongly_connected_component_from'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
lago-api  |     from /usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/initializable.rb:60:in `run_initializers'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/application.rb:426:in `initialize!'
lago-api  |     from /app/config/environment.rb:7:in `<main>'
lago-api  |     from config.ru:5:in `require_relative'
lago-api  |     from config.ru:5:in `block in <main>'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:116:in `eval'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:116:in `new_from_string'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:105:in `load_file'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:66:in `parse_file'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:349:in `build_app_and_options_from_config'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:249:in `app'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:422:in `wrapped_app'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:312:in `block in start'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:379:in `handle_profiling'
lago-api  |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:311:in `start'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:38:in `start'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:145:in `block in perform'
lago-api  |     from <internal:kernel>:90:in `tap'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:136:in `perform'
lago-api  |     from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
lago-api  |     from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'
lago-api  |     from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
lago-api  |     from /usr/local/bundle/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
lago-api  |     from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
lago-api  |     from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
lago-api  |     from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
lago-api  |     from bin/rails:4:in `<main>'
```

**Comment by jdenquin** [comment]
it seems you miss your RSA Private Key

```# Set up environment configuration
echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env
source .env
```

**Comment by kylebown1** [comment]
I'm also having problems with the RSA Key, I've tried everything. For some reason docker reports back in inspect either a shorter key or a completly different key each time doesnt make sense

**Comment by jdenquin** [comment]
@kylebown1 do you use the `.env` file?
can you try passing it to `docker compose` ?

**Comment by juandl** [comment]
Yeah, Docs needs a good update; RSA has spaces and etc., so Docker won't take it well. 

Use this instead; that should generate the RSA and keep the spaces safe for ENV format.

`openssl genrsa 2048 | base64 | tr -d '\n'`

**Comment by jdenquin** [comment]
@guleng do you still have the issue?
